--task1
SELECT  MAX(AUDITORIUM_CAPACITY) [люйяхлюкэмюъ блеярхлнярэ],
		MIN(AUDITORIUM_CAPACITY) [лхмхлюкэмюъ блеярхлнярэ],
		SUM(AUDITORIUM_CAPACITY) [ясллюпмюъ блеярхлнярэ],
		AVG(AUDITORIUM_CAPACITY) [ярпедмъъ блеярхлнярэ],
		COUNT(*) [йнкхвеярбн юсдхрнпхи]
FROM AUDITORIUM

--task2
SELECT  AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, 
		MAX(AUDITORIUM_CAPACITY) [люйяхлюкэмюъ блеярхлнярэ],
		MIN(AUDITORIUM_CAPACITY) [лхмхлюкэмюъ блеярхлнярэ],
		SUM(AUDITORIUM_CAPACITY) [ясллюпмюъ блеярхлнярэ],
		AVG(AUDITORIUM_CAPACITY) [ярпедмъъ блеярхлнярэ],
		COUNT(*) [йнкхвеярбн юсдхрнпхи]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	GROUP BY AUDITORIUM_TYPENAME

--task3
SELECT *
	FROM (SELECT CASE 
			WHEN NOTE BETWEEN 4 AND 5 THEN '4-5'
			WHEN NOTE BETWEEN 6 AND 7 THEN '6-7'
			WHEN NOTE BETWEEN 8 AND 9 THEN '8-9'
			WHEN NOTE = 10 THEN '10'
			ELSE 'МЕР НРЛЕРНЙ'
			END [НЖЕМЙХ], COUNT(*) [ЙНКХВЕЯРБН]
				FROM PROGRESS GROUP BY CASE
					WHEN NOTE BETWEEN 4 AND 5 THEN '4-5'
					WHEN NOTE BETWEEN 6 AND 7 THEN '6-7'
					WHEN NOTE BETWEEN 8 AND 9 THEN '8-9'
					WHEN NOTE = 10 THEN '10'
					ELSE 'МЕР НРЛЕРНЙ'
					END) AS L
	ORDER BY CASE [НЖЕМЙХ]
	 WHEN '10' THEN 1
	 WHEN '8-9' THEN 2
	 WHEN '6-7' THEN 3
	 WHEN '4-5' THEN 4
	 ELSE 0
	 END

--task4
SELECT	FACULTY.FACULTY[ТЮЙСКЭРЕР], GROUPS.PROFESSION[ЯОЕЖХЮКЭМНЯРЭ],
		GROUPS.COURSE[ЙСПЯ], ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[ЯПЕДМЪЪ НЖЕМЙЮ]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE PROGRESS.SUBJECT = 'ад' OR PROGRESS.SUBJECT = 'нюХо'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE
ORDER BY [ЯПЕДМЪЪ НЖЕМЙЮ] DESC

--task5
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY ROLLUP (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

--task6
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY CUBE (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

--task7
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION 
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('урХр')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT

SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION ALL
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('урХр')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT

--task8
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
INTERSECT
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('урХр')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT

SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('урХр')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT
EXCEPT
SELECT	GROUPS.PROFESSION[яоежхюкэмнярэ], PROGRESS.SUBJECT[дхяжхокхмю],
		ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2)[япедмъъ нжемйю]
FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY IN ('рнб')
GROUP BY FACULTY.FACULTY,GROUPS.PROFESSION, PROGRESS.SUBJECT

--task10
SELECT P1.SUBJECT[дхяжхокхмю],
	(SELECT COUNT(*) FROM PROGRESS P2
	WHERE	P1.SUBJECT = P2.SUBJECT AND P1.NOTE = P2.NOTE)[йнк-бн]
FROM PROGRESS P1
GROUP BY SUBJECT, NOTE
HAVING NOTE BETWEEN 8 AND 9

--SELECT SUBJECT, COUNT(*)
--	FROM PROGRESS
--	WHERE NOTE BETWEEN 8 AND 9
--GROUP BY SUBJECT


