--task1
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME 
	FROM FACULTY, PULPIT
	WHERE PULPIT.FACULTY = FACULTY.FACULTY
		AND FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
											WHERE PROFESSION.PROFESSION_NAME LIKE '%технологии%' OR
												  PROFESSION.PROFESSION_NAME LIKE '%технология%')

---task2
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME 
	FROM FACULTY INNER JOIN PULPIT
	ON	PULPIT.FACULTY = FACULTY.FACULTY
		WHERE FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
											WHERE PROFESSION.PROFESSION_NAME LIKE '%технологии%' OR
												  PROFESSION.PROFESSION_NAME LIKE '%технология%')

--task3
SELECT TOP 2 PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
	FROM FACULTY INNER JOIN PULPIT
	ON	PULPIT.FACULTY = FACULTY.FACULTY
		INNER JOIN PROFESSION
		ON FACULTY.FACULTY = PROFESSION.FACULTY
			WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологии%' OR
				  PROFESSION.PROFESSION_NAME LIKE '%технология%')

--task4
SELECT AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE 
	FROM AUDITORIUM a
	WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
		WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
											ORDER BY AUDITORIUM_CAPACITY DESC)
	ORDER BY AUDITORIUM_CAPACITY DESC

--task5
SELECT FACULTY.FACULTY_NAME FROM FACULTY
	WHERE NOT EXISTS (SELECT * FROM PULPIT 
							WHERE FACULTY.FACULTY = PULPIT.FACULTY)

--task6
SELECT TOP 1 (SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT = 'ОАиП')[ОАиП],
       (SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT = 'БД')[БД],
	   (SELECT AVG(PROGRESS.NOTE) FROM PROGRESS WHERE PROGRESS.SUBJECT = 'СУБД')[СУБД]
FROM PROGRESS

--task7
SELECT PROGRESS.SUBJECT, PROGRESS.NOTE FROM PROGRESS
	WHERE PROGRESS.NOTE > ALL (SELECT PROGRESS.NOTE FROM PROGRESS
									WHERE PROGRESS.SUBJECT = 'КГ')

--task8
SELECT PROGRESS.SUBJECT, PROGRESS.NOTE FROM PROGRESS
	WHERE PROGRESS.NOTE > ANY (SELECT PROGRESS.NOTE FROM PROGRESS
									WHERE PROGRESS.SUBJECT = 'КГ')
	