use S_UNIVER

--task1
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
	FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

--task2
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
	FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%'

--task3
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
	FROM AUDITORIUM, AUDITORIUM_TYPE
	WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

--task4
SELECT FACULTY.FACULTY[Факультет], PULPIT.PULPIT[Кафедра], GROUPS.PROFESSION[Специальность],
	   SUBJECT.SUBJECT[Дисциплина], STUDENT.NAME[Имя_студента],
	   CASE
		   WHEN (PROGRESS.NOTE = 6) THEN 'Шесть'
		   WHEN (PROGRESS.NOTE = 7) THEN 'Семь'
		   WHEN (PROGRESS.NOTE = 8) THEN 'Восемь'
	   END [Оценка]
	   FROM STUDENT INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
	   INNER JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
	   INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	   INNER JOIN SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT
	   INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	   WHERE PROGRESS.NOTE BETWEEN 6 AND 8
	   --ORDER BY FACULTY.FACULTY asc, PULPIT.PULPIT asc, STUDENT.NAME asc,
				--PROGRESS.NOTE desc
	   ORDER BY
	   (CASE 
			WHEN(PROGRESS.NOTE = 6) THEN 3
			WHEN(PROGRESS.NOTE = 7) THEN 1
			WHEN(PROGRESS.NOTE = 8) THEN 2
		end)
 	
--task6
SELECT (PULPIT.PULPIT_NAME)[Кафедра], isnull(TEACHER.TEACHER_NAME, '***')[Преподаватель]
	FROM PULPIT LEFT OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT

--task7-1
SELECT (PULPIT.PULPIT_NAME)[Кафедра], isnull(TEACHER.TEACHER_NAME, '***')[Преподаватель]
	FROM TEACHER LEFT OUTER JOIN PULPIT
	ON TEACHER.PULPIT = PULPIT.PULPIT
--task7-2
SELECT (PULPIT.PULPIT_NAME)[Кафедра], isnull(TEACHER.TEACHER_NAME, '***')[Преподаватель]
	FROM PULPIT RIGHT OUTER JOIN TEACHER
	ON PULPIT.PULPIT = TEACHER.PULPIT

--task8
SELECT * FROM AUDITORIUM LEFT OUTER JOIN AUDITORIUM_TYPE
		 ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM RIGHT OUTER JOIN AUDITORIUM_TYPE
		 ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
		 ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

--task9
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
	FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
	WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 